### ISSUE TITLE
Problem with dedicated server and server.properties

### ISSUE THREAD

**Issue by calloatti** [valoeghese/ClimaticWorldType#1]
MC 1.14.4
mods folder:
climaticworldtype-1.1.0.jar
fabric-api-0.3.1+build.208.jar

I set `level-type=climatic` in `server.properties` start the server without a `world` folder, and after the server starts and the world gets generated, this happens:

`level-type=climatic` in `server.properties` gets changed to `level-type=default`

If I check the `world\level.dat`, I see `generatorName=default`

**Comment by valoeghese** [comment]
hmmm
