### ISSUE TITLE
No Ocean Structures

### ISSUE THREAD

**Issue by VogelBoi** [valoeghese/ClimaticWorldType#2]
No Ocean Structures generate.
Tested on 2 different computers.
Both using only the mod itself and fabric api in the mods folder.
Tried resetting config, didn't work either.
Tested on 1.14 and 1.14.4, didn't work on both versions.
Structures generate as expected with other world types.
All other structures can be located.
When trying to search for any ocean structure with /locate, you get "Could not find that structure nearby" as instant response.

**Comment by valoeghese** [comment]
Found the problem in the code. A hotfix will be available shortly :)
